#remote_theme: pages-themes/leap-day@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
theme: jekyll-theme-cayman
title: 2024年度 多変数関数論冬セミナー
# description: 2024年12月13-15日
# theme: jekyll-theme-cayman

